/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module random_round_genrator_11 (
    input clk,
    input rst,
    input generate_next,
    output reg [7:0] out
  );
  
  
  
  wire [32-1:0] M_ctr_value;
  counter_19 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  wire [32-1:0] M_random_number_generator_num;
  reg [1-1:0] M_random_number_generator_next;
  reg [32-1:0] M_random_number_generator_seed;
  pn_gen_20 random_number_generator (
    .clk(clk),
    .rst(rst),
    .next(M_random_number_generator_next),
    .seed(M_random_number_generator_seed),
    .num(M_random_number_generator_num)
  );
  
  reg [4:0] rng_out;
  
  localparam ROUND_DETAILS = 256'h6a645a524a413a342c241c110a04898179716a645a524a413a2c24241c110a04;
  
  always @* begin
    M_random_number_generator_seed = M_ctr_value;
    M_random_number_generator_next = generate_next;
    rng_out = M_random_number_generator_num[0+4-:5];
    out = ROUND_DETAILS[(rng_out)*8+7-:8];
  end
endmodule
