/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_18 (
    input z,
    input v,
    input n,
    input [1:0] alufn_signal_2_1,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] s;
  
  always @* begin
    s[1+14-:15] = 15'h0000;
    
    case (alufn_signal_2_1)
      2'h1: begin
        s[0+0-:1] = z;
      end
      2'h2: begin
        s[0+0-:1] = n ^ v;
      end
      2'h3: begin
        s[0+0-:1] = z | (n ^ v);
      end
    endcase
    out = s;
  end
endmodule
