/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 32
     DIV = 0
     TOP = 32h1111
     UP = 1
*/
module counter_19 (
    input clk,
    input rst,
    output reg [31:0] value
  );
  
  localparam SIZE = 6'h20;
  localparam DIV = 1'h0;
  localparam TOP = 32'h00001111;
  localparam UP = 1'h1;
  
  
  reg [31:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 32'h00001111;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q;
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 32'h00001111) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 32'h00001111;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
