/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_17 (
    input [15:0] a,
    input [3:0] b,
    input [1:0] alufn_signal_1_0,
    output reg [15:0] out
  );
  
  
  
  integer unsigned_b;
  
  always @* begin
    unsigned_b = $unsigned(b);
    
    case (alufn_signal_1_0)
      2'h0: begin
        out = a << unsigned_b;
      end
      2'h1: begin
        out = a >> unsigned_b;
      end
      2'h3: begin
        out = $signed(a) >>> unsigned_b;
      end
      default: begin
        out = a;
      end
    endcase
  end
endmodule
